# .circleci/config.yml file
version: 2.1

jobs:
  build_and_push:
    docker:
      - image: cimg/base:current # Docker image that installs Docker and has Git,
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Build Docker images
          command: |
            docker build -t udagram-api-feed ./udagram-api-feed
            docker build -t udagram-api-user ./udagram-api-user
            docker build -t udagram-frontend ./udagram-frontend
            docker build -t udagram-api-reverse-proxy ./udagram-api-reverse-proxy
      - run:
          name: Tag Docker images
          command: |
            TIMESTAMP=$(date +"%Y%m%d%H%M%S")
            docker tag udagram-api-feed txphuc97/udagram-api-feed:${TIMESTAMP}
            docker tag udagram-api-user txphuc97/udagram-api-user:${TIMESTAMP}
            docker tag udagram-frontend txphuc97/udagram-frontend:${TIMESTAMP}
            docker tag udagram-api-reverse-proxy txphuc97/udagram-api-reverse-proxy:${TIMESTAMP}
      - run:
          name: Login to DockerHub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Push Docker images
          command: |
            TIMESTAMP=$(date +"%Y%m%d%H%M%S")
            docker push txphuc97/udagram-api-feed:${TIMESTAMP}
            docker push txphuc97/udagram-api-user:${TIMESTAMP}
            docker push txphuc97/udagram-frontend:${TIMESTAMP}
            docker push txphuc97/udagram-api-reverse-proxy:${TIMESTAMP}

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_push
